/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_unitn_ing_rista_util_SpaceGroups */

#ifndef _Included_it_unitn_ing_rista_util_SpaceGroups
#define _Included_it_unitn_ing_rista_util_SpaceGroups
#ifdef __cplusplus
extern "C" {
#endif
#undef it_unitn_ing_rista_util_SpaceGroups_CONV_NUMBER
#define it_unitn_ing_rista_util_SpaceGroups_CONV_NUMBER 0L
#undef it_unitn_ing_rista_util_SpaceGroups_CONV_SCHOENFLIES
#define it_unitn_ing_rista_util_SpaceGroups_CONV_SCHOENFLIES 1L
#undef it_unitn_ing_rista_util_SpaceGroups_CONV_HM
#define it_unitn_ing_rista_util_SpaceGroups_CONV_HM 2L
#undef it_unitn_ing_rista_util_SpaceGroups_CONV_HALL
#define it_unitn_ing_rista_util_SpaceGroups_CONV_HALL 3L
/*
 * Class:     it_unitn_ing_rista_util_SpaceGroups
 * Method:    testCCTBXForMaud
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_it_unitn_ing_rista_util_SpaceGroups_testCCTBXForMaud
  (JNIEnv *, jclass);

/*
 * Class:     it_unitn_ing_rista_util_SpaceGroups
 * Method:    getAllSymmetriesAndSpaceGroups
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_it_unitn_ing_rista_util_SpaceGroups_getAllSymmetriesAndSpaceGroups
  (JNIEnv *, jclass);

/*
 * Class:     it_unitn_ing_rista_util_SpaceGroups
 * Method:    checkSpaceGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lit/unitn/ing/rista/util/Spacegroup;
 */
JNIEXPORT jobject JNICALL Java_it_unitn_ing_rista_util_SpaceGroups_checkSpaceGroup
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
