package it.unitn.ing.fortran;

/* Generated By:JavaCC: Do not edit this line. FormatParserConstants.java */

public interface FormatParserConstants {

  int EOF = 0;
  int INTEGER = 2;
  int STRING = 3;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<INTEGER>",
    "<STRING>",
    "\"A\"",
    "\"I\"",
    "\"F\"",
    "\".\"",
    "\"E\"",
    "\"X\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
