package it.unitn.ing.fortran;

/* Generated By:JavaCC: Do not edit this line. NumberParserConstants.java */

public interface NumberParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 1;
  int DECIMAL_LITERAL = 2;
  int FLOATING_POINT_LITERAL = 3;
  int EXPONENT = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\" \"",
    "\"-\"",
    "\"+\"",
  };

}
