package it.unitn.ing.fortran;

/* Generated By:JavaCC: Do not edit this line. ParseError.java Version 0.7pre1 */

public class ParseError extends Exception {
  public ParseError() {
  }

  public ParseError(String message) {
    super(message);
  }
}
