/*
 * @(#)NeuralNetworkGraphPanel.java created Mar 22, 2006 Casalino
 *
 * Copyright (c) 1996-2006 Luca Lutterotti All Rights Reserved.
 *
 * This software is the research result of Luca Lutterotti and it is 
 * provided as it is as confidential and proprietary information.  
 * You shall not disclose such Confidential Information and shall use 
 * it only in accordance with the terms of the license agreement you 
 * entered into with the author.
 *
 * THE AUTHOR MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
 * SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE, OR NON-INFRINGEMENT. THE AUTHOR SHALL NOT BE LIABLE FOR ANY DAMAGES
 * SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
 * THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

package it.unitn.ing.rista.neuralnetwork;

import javax.swing.border.TitledBorder;
import javax.swing.border.EmptyBorder;
import java.awt.*;


/**
 * The NeuralNetworkGraphPanel is a class
 * <p/>
 * Description
 *
 * @author Luca Lutterotti
 * @version $Revision: 1.1 $, $Date: 2006/07/20 14:06:04 $
 * @since JDK1.1
 */

public class NeuralNetworkGraphPanel extends javax.swing.JPanel {

    /** Creates new form NeuralNetworkGraphPanel */
    public NeuralNetworkGraphPanel() {
        initComponents();

        setBorder( new TitledBorder(new EmptyBorder(0, 0, 0, 0),
            "Error Graph",
            TitledBorder.LEFT,
            TitledBorder.TOP));

        neuralNetworkGraph = new NeuralNetworkGraph();
        add(neuralNetworkGraph, BorderLayout.NORTH);
    }


    public void clear() {
        neuralNetworkGraph.clear();
        // Update immediately.
        neuralNetworkGraph.repaint();
    }

    public NeuralNetworkGraph getNeuralNetworkGraph() {
        return neuralNetworkGraph;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private NeuralNetworkGraph neuralNetworkGraph;


}
