/*
 * @(#)SpectrumScholarPanel.java created Mar 23, 2006 Casalino
 *
 * Copyright (c) 1996-2004 Luca Lutterotti All Rights Reserved.
 *
 * This software is the research result of Luca Lutterotti and it is 
 * provided as it is as confidential and proprietary information.  
 * You shall not disclose such Confidential Information and shall use 
 * it only in accordance with the terms of the license agreement you 
 * entered into with the author.
 *
 * THE AUTHOR MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
 * SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE, OR NON-INFRINGEMENT. THE AUTHOR SHALL NOT BE LIABLE FOR ANY DAMAGES
 * SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
 * THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

package it.unitn.ing.rista.neuralnetwork;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;


/**
 * The SpectrumScholarPanel is a class
 * <p/>
 * Description
 *
 * @author Luca Lutterotti
 * @version $Revision: 1.1 $, $Date: 2006/07/20 14:06:04 $
 * @since JDK1.1
 */

public class SpectrumScholarPanel extends JPanel {

  ProjectEnvironment projectEnvironment;
  NeuralNetworkPanel neuralNetworkPanel;
  SpectrumRecognitionPanel spectrumRecognitionPanel;
  private JTextField statusField;

  NumberSpectrum inputSpectrum = null;

  private static final int PREFERRED_WIDTH = 630;
  private static final int PREFERRED_HEIGHT = 500;

  /**
   * Creates new form SpectrumScholarPanel
   */
  public SpectrumScholarPanel(NumberSpectrum inputSpectrum) {
    this.inputSpectrum = inputSpectrum;
    projectEnvironment = new ProjectEnvironment();
    initComponents();

    JTabbedPane tabbedPane = new JTabbedPane();

//    numberImagePanel = new NumberImagePanel();
    neuralNetworkPanel = new NeuralNetworkPanel();
    spectrumRecognitionPanel = new SpectrumRecognitionPanel();

/*    tabbedPane.addTab(MyResourceBundle.getString("TAB_NUMBER_IMAGE"),
          createImageIcon("stock-select-color.png", null),
          numberImagePanel,
          MyResourceBundle.getString("TAB_NUMBER_IMAGE_TOOLTIP"));
*/
    tabbedPane.addTab("Neural Network",
          null,
          neuralNetworkPanel,
          "Teaching the neural network to recognize spectra");

    tabbedPane.addTab("Spectrum Recognition",
          null,
          spectrumRecognitionPanel,
          "Recognizing the input spectrum");

    tabbedPane.setMnemonicAt(0, KeyEvent.VK_1);
    tabbedPane.setMnemonicAt(1, KeyEvent.VK_2);
    tabbedPane.setMnemonicAt(2, KeyEvent.VK_3);

    add(tabbedPane, BorderLayout.CENTER);

    statusField = new JTextField("");
    statusField.setEditable(false);
    add(statusField, BorderLayout.SOUTH);

    // At least update one time during the startup.
    this.updateTabbedPaneInfo();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents

    setLayout(new java.awt.BorderLayout());

    setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
  }//GEN-END:initComponents

  public Dimension getPreferredSize() {
    return new Dimension(PREFERRED_WIDTH, PREFERRED_HEIGHT);
  }

  public ProjectEnvironment getProjectEnvironment() {
    return projectEnvironment;
  }

  public NeuralNetworkPanel getNeuralNetworkPanel() {
    return neuralNetworkPanel;
  }

  public SpectrumRecognitionPanel getSpectrumRecognitionPanel() {
    return spectrumRecognitionPanel;
  }

  public NumberSpectrum getNumberSpectrum() {
      return inputSpectrum;
  }

  public void updateTabbedPaneInfo() {
//    numberImagePanel.updateInfo();
    neuralNetworkPanel.updateInfo();
    spectrumRecognitionPanel.updateInfo();
  }

  public void setStatusField(String status) {
    statusField.setText(status);
  }

}
