# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MAUD - Materials Analysis Using Diffraction (and more)
email: luca.lutterotti@unitn.it
description: >- # this means to ignore newlines until "baseurl:"
  MAUD software can analysis diffraction and other spectroscopic data by fitting
  all your pattern/spectra using an unified model in a Rietveld like refinement. 
  This enable you to get more info on your materials or chemical compounds including: 
  phases content and crystal structures, microstructural characteristics like size
  and strains, crystallographic texture and planar defects. It works for amorphous or 
  nanomaterials too. Can use X-ray, neutron or electron data, diffraction, reflectivity
  or fluorescence.
baseurl: "/maud" # the subpath of your site, e.g. /blog
url: "https://luttero.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MaudProgram
github_username:  luttero

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
